version: '3.8'
networks:
  private:

services:
  broker:
    image: eclipse-mosquitto:latest
    container_name: broker
    restart: always
    volumes:
      - ./.broker/config:/mosquitto/config
      - ./.broker/data:/mosquitto/data
      - ./.broker/log:/mosquitto/log
      
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - private

  api:
    build: ./api/
    container_name: api
    ports: 
      - 8000:8000
    environment:
      - MQTT_BROKER=broker
      - MQTT_TOPIC=test
      - MQTT_PORT=1883  
    networks:
      - private
    depends_on:
      - broker

  mail:
    build: ./mail/
    container_name: mail
    environment:
      - MQTT_BROKER=broker
      - MQTT_TOPIC=test   
      - MQTT_PORT=1883
    networks:
      - private
    command: 
      - python3 
      - -u 
      - mail.py 
    depends_on:
      - api